### ISSUE TITLE
Unable to find maintainer

### ISSUE THREAD

**Issue by dardevelin** [lllacher/resume#1]
Hi Lisa, can't seem to reach you, did you change your contact ?
best
dbs

**Comment by lllacher** [comment]
Hi Darcy,

I just got back into the country last night/early this morning.  I am sorry
I have been unavailable.  I had expected that I would have internet access
while gone, but that did not prove out.  I will plan on meeting with you
next Monday if that works.

Thanks,

Lisa

**Comment by dardevelin** [comment]
any updates on times ?

**Comment by lllacher** [comment]
Can we try for next Tuesday at 9:30 a.m. ?

**Comment by dardevelin** [comment]
@lllacher Let's aim for that
